name: race_demo
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue:
    path: plugs/flutter_blue-0.6.0+1
  path_provider: ^1.2.0
  dio: ^2.1.13
  permission_handler: ^3.2.1+1
  bloc: ^0.14.4
  flutter_bloc: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  #不要升级 test的版本, 因为高版本不兼容当前sdk
  test: ^1.6.3


flutter:

  uses-material-design: true

